import React, { useState } from 'react';
import axios from 'axios';
import ReactMarkdown from 'react-markdown';
import { API_BASE } from '../../config';
import { ClipboardCheck, Target, AlertCircle, Download, FileText } from 'lucide-react';

const AnswerEvaluator = () => {
  const [question, setQuestion] = useState('');
  const [answer, setAnswer] = useState('');
  const [loading, setLoading] = useState(false);
  const [evaluation, setEvaluation] = useState('');
  const [error, setError] = useState('');

  const handleDownloadMD = async () => {
    if (!evaluation) return;
    try {
      const response = await axios.post(`${API_BASE}/api/export/save-local`, {
        title: `Evaluation Report`,
        content: `# Exam Evaluation Report\n\n**Question**: ${question}\n\n---\n\n${evaluation}\n\n---\nGenerated by Legaify.ai`
      });
      alert(`Success! Saved to your Downloads folder: \n${response.data.filename}`);
    } catch (err) {
      alert("Failed to save file.");
    }
  };

  const handleEvaluate = async () => {
    if (!question || !answer) return;
    setLoading(true);
    setError('');
    setEvaluation('');

    try {
      const response = await axios.post(`${API_BASE}/api/tutor/evaluate`, {
        question: question,
        student_answer: answer
      });
      setEvaluation(response.data.content);
    } catch (err) {
      setError('Failed to evaluate answer. Please check your connection.');
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="evaluator fade-in">
      <div className="evaluator-header" style={{marginBottom: '30px'}}>
        <h1 className="serif gradient-text">AI Answer Examiner</h1>
        <p className="text-muted">Submit your exam answer for a detailed evaluation based on KSLU patterns.</p>
      </div>

      <div className="evaluator-grid" style={{display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '30px'}}>
        <div className="input-side card">
          <div className="form-group" style={{marginBottom: '20px'}}>
            <label style={{display: 'block', fontWeight: '700', marginBottom: '8px'}}>Exam Question</label>
            <input 
              type="text" 
              placeholder="Paste the question here..." 
              value={question}
              onChange={(e) => setQuestion(e.target.value)}
              style={{width: '100%', padding: '12px', borderRadius: '8px', border: '1px solid var(--border)'}}
            />
          </div>
          <div className="form-group" style={{marginBottom: '20px'}}>
            <label style={{display: 'block', fontWeight: '700', marginBottom: '8px'}}>Your Answer</label>
            <textarea 
              rows="15"
              placeholder="Write or paste your answer here..." 
              value={answer}
              onChange={(e) => setAnswer(e.target.value)}
              style={{width: '100%', padding: '12px', borderRadius: '8px', border: '1px solid var(--border)', fontFamily: 'inherit'}}
            />
          </div>
          <button className="btn btn-primary" style={{width: '100%'}} onClick={handleEvaluate} disabled={loading}>
            {loading ? 'Evaluating...' : 'Get Final Score & Feedback'}
          </button>
        </div>

        <div className="result-side">
          {loading && (
            <div className="loading-state card glass h-full">
              <div className="spinner"></div>
              <p>Analyzing structure, legal accuracy, and terminology...</p>
            </div>
          )}

          {evaluation && (
            <div className="evaluation-report card fade-in">
              <div className="content-header" style={{display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '20px'}}>
                <div>
                  <span className="badge-kslu">Examiner Feedback</span>
                  <h3>Evaluation Report</h3>
                </div>
                <button 
                  className="btn btn-outline" 
                  onClick={handleDownloadMD}
                  style={{display: 'flex', alignItems: 'center', gap: '8px', padding: '8px 12px'}}
                >
                  <Download size={16} /> PDF
                </button>
              </div>
              <div className="markdown-body">
                <ReactMarkdown>{evaluation}</ReactMarkdown>
              </div>
            </div>
          )}

          {!loading && !evaluation && (
            <div className="empty-state card glass" style={{height: '100%', display: 'flex', flexDirection: 'column', justifyContent: 'center'}}>
              <ClipboardCheck size={64} color="#e2e8f0" />
              <h3>Evaluation Result</h3>
              <p>Your detailed feedback will appear here after evaluation.</p>
            </div>
          )}
        </div>
      </div>
    </div>
  );
};

export default AnswerEvaluator;
