import React, { useState } from 'react';
import axios from 'axios';
import ReactMarkdown from 'react-markdown';
import { API_BASE } from '../../config';
import { Search, Gavel, Download, FileText } from 'lucide-react';
import './Tutor.css'; // Reusing some base components

const CaseSummarizer = () => {
  const [caseName, setCaseName] = useState('');
  const [loading, setLoading] = useState(false);
  const [summary, setSummary] = useState('');
  const [error, setError] = useState('');

  const handleDownloadMD = async () => {
    if (!summary) return;
    try {
      const response = await axios.post(`${API_BASE}/api/export/save-local`, {
        title: `Case Summary ${caseName}`,
        content: `# Case Summary: ${caseName}\n\n${summary}\n\n---\nGenerated by Legaify.ai`
      });
      alert(`Success! Saved to your Downloads folder: \n${response.data.filename}`);
    } catch (err) {
      alert("Failed to save file.");
    }
  };

  const handleSummarize = async () => {
    if (!caseName) return;
    setLoading(true);
    setError('');
    setSummary('');

    try {
      const response = await fetch(`${API_BASE}/api/tutor/case-summary`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ case_name: caseName })
      });

      if (!response.ok) throw new Error("Failed to fetch case summary.");
      
      const reader = response.body.getReader();
      const decoder = new TextDecoder('utf-8');
      
      let isFirstChunk = true;

      while (true) {
        const { done, value } = await reader.read();
        if (done) break;
        
        if (isFirstChunk) {
          setLoading(false);
          isFirstChunk = false;
        }
        
        const chunk = decoder.decode(value, { stream: true });
        setSummary((prev) => prev + chunk);
      }
    } catch (err) {
      setLoading(false);
      setError('Failed to fetch case summary. Please check your connection.');
    }
  };

  return (
    <div className="case-summarizer fade-in">
      <div className="card glass-dark" style={{maxWidth: '800px', margin: '0 auto', textAlign: 'center'}}>
        <Scale size={48} color="#d4af37" style={{marginBottom: '20px'}} />
        <h2 className="serif">Case Law Summarizer</h2>
        <p className="text-muted">Enter any landmark or KSLU relevant case for a crisp summary.</p>
        
        <div className="search-group" style={{marginTop: '30px', display: 'flex', gap: '10px'}}>
          <input 
            type="text" 
            placeholder="e.g. Kesavananda Bharati v. State of Kerala..." 
            value={caseName}
            onChange={(e) => setCaseName(e.target.value)}
            style={{flex: 1, padding: '12px 20px', borderRadius: '10px', border: '1px solid var(--border)'}}
          />
          <button className="btn btn-primary" onClick={handleSummarize} disabled={loading}>
            {loading ? 'Analyzing...' : 'Summarize'}
          </button>
        </div>

        {error && <div className="error-message">{error}</div>}
      </div>

      <div className="summary-result" style={{marginTop: '40px'}}>
        {loading && (
          <div className="loading-state card glass">
            <div className="spinner"></div>
            <p>Analyzing judgment and extracting legal principles...</p>
          </div>
        )}

        {summary && (
          <div className="explanation-content card fade-in">
            <div className="content-header" style={{display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '20px'}}>
              <div>
                <span className="badge-kslu">Legal Principle & Summary</span>
                <h2>{caseName}</h2>
              </div>
              <button 
                className="btn btn-outline" 
                onClick={handleDownloadMD}
                style={{display: 'flex', alignItems: 'center', gap: '8px', padding: '8px 16px'}}
              >
                <Download size={18} /> Download PDF
              </button>
            </div>
            <div className="markdown-body">
              <ReactMarkdown>{summary}</ReactMarkdown>
            </div>
          </div>
        )}
      </div>
    </div>
  );
};

// Simple icon for empty state
const Scale = ({ size, color, style }) => (
  <svg style={style} width={size} height={size} viewBox="0 0 24 24" fill="none" stroke={color} strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
    <path d="m16 16 3-8 3 8c-.87.65-1.92 1-3 1s-2.13-.35-3-1Z"></path>
    <path d="m2 16 3-8 3 8c-.87.65-1.92 1-3 1s-2.13-.35-3-1Z"></path>
    <path d="M7 21h10"></path>
    <path d="M12 3v18"></path>
    <path d="M3 7h18"></path>
  </svg>
);

export default CaseSummarizer;
