import React, { useState } from 'react';
import axios from 'axios';
import ReactMarkdown from 'react-markdown';
import { API_BASE } from '../../config';
import { Upload, MessageSquare, FileText, Send, CheckCircle2, RotateCcw, Download } from 'lucide-react';

const DocumentTutor = () => {
  const [file, setFile] = useState(null);
  const [docId, setDocId] = useState(null);
  const [loading, setLoading] = useState(false);
  const [chatLoading, setChatLoading] = useState(false);
  const [messages, setMessages] = useState([]);
  const [input, setInput] = useState('');
  const [filename, setFilename] = useState('');

  const handleDownloadMD = async () => {
    if (messages.length === 0) return;
    const chatHistory = messages.map(m => `**${m.role.toUpperCase()}**: ${m.content}`).join('\n\n');
    try {
      const response = await axios.post(`${API_BASE}/api/export/save-local`, {
        title: `Document Chat Notes`,
        content: `# Document Chat: ${filename}\n\n${chatHistory}\n\n---\nGenerated by Legaify.ai`
      });
      alert(`Success! Saved to your Downloads folder: \n${response.data.filename}`);
    } catch (err) {
      alert("Failed to save file.");
    }
  };

  const handleFileUpload = async (e) => {
    const selectedFile = e.target.files[0];
    if (!selectedFile) return;

    setLoading(true);
    const formData = new FormData();
    formData.append('file', selectedFile);

    try {
      const response = await axios.post(`${API_BASE}/api/docs/upload`, formData);
      setDocId(response.data.doc_id);
      setFilename(response.data.filename);
      setMessages([{ role: 'assistant', content: `Uploaded **${response.data.filename}**. You can now ask questions or request a summary!` }]);
    } catch (err) {
      console.error(err);
      alert('Failed to upload document.');
    } finally {
      setLoading(false);
    }
  };

  const handleSendMessage = async () => {
    if (!input || !docId) return;

    const userMessage = { role: 'user', content: input };
    setMessages(prev => [...prev, userMessage]);
    setInput('');
    setChatLoading(true);

    try {
      const response = await axios.post(`${API_BASE}/api/docs/chat`, {
        doc_id: docId,
        question: input
      });
      setMessages(prev => [...prev, { role: 'assistant', content: response.data.content }]);
    } catch (err) {
      alert('Error communicating with AI.');
    } finally {
      setChatLoading(false);
    }
  };

  const handleSummarize = async () => {
    if (!docId) return;
    setChatLoading(true);

    try {
      const response = await axios.post(`${API_BASE}/api/docs/summarize`, null, {
        params: { doc_id: docId }
      });
      setMessages(prev => [...prev, { role: 'assistant', content: `### Summary of ${filename}\n\n${response.data.content}` }]);
    } catch (err) {
      alert('Error generating summary.');
    } finally {
      setChatLoading(false);
    }
  };

  return (
    <div className="doc-tutor fade-in">
      <div className="planner-header">
        <h1 className="serif gradient-text">Document AI Tutor</h1>
        <p className="text-muted">Upload notes, judgments, or textbooks and get instant AI-powered insights.</p>
      </div>

      {!docId ? (
        <div className="upload-section card glass fade-in" style={{textAlign: 'center', padding: '60px 20px'}}>
          <Upload size={64} color="#1e3a8a" style={{marginBottom: '20px'}} />
          <h2>Drop your legal documents here</h2>
          <p className="text-muted" style={{marginBottom: '30px'}}>Supports PDF, Word (.docx), and Text files.</p>
          
          <label className="btn btn-primary" style={{cursor: 'pointer'}}>
            {loading ? 'Processing Document...' : 'Select File'}
            <input type="file" onChange={handleFileUpload} hidden disabled={loading} accept=".pdf,.docx,.txt" />
          </label>
        </div>
      ) : (
        <div className="chat-interface grid" style={{display: 'grid', gridTemplateColumns: '1fr', gap: '20px'}}>
          <div className="chat-window card glass" style={{height: '600px', display: 'flex', flexDirection: 'column'}}>
            <div className="chat-header" style={{display: 'flex', justifyContent: 'space-between', padding: '15px', borderBottom: '1px solid var(--border)'}}>
              <div style={{display: 'flex', alignItems: 'center', gap: '10px'}}>
                <FileText size={20} color="#1e3a8a" />
                <span style={{fontWeight: 600}}>{filename}</span>
              </div>
               <div style={{display: 'flex', gap: '8px'}}>
                <button className="btn btn-sm btn-outline" onClick={handleDownloadMD} title="Save Notes as PDF">
                  <Download size={14} /> PDF
                </button>
                <button className="btn btn-sm" onClick={handleSummarize} disabled={chatLoading}>Summarize</button>
                <button className="btn btn-sm btn-outline" onClick={() => {setDocId(null); setMessages([]);}}><RotateCcw size={14} /></button>
              </div>
            </div>

            <div className="chat-messages" style={{flex: 1, overflowY: 'auto', padding: '20px'}}>
              {messages.map((m, i) => (
                <div key={i} className={`message ${m.role}`} style={{marginBottom: '20px', textAlign: m.role === 'user' ? 'right' : 'left'}}>
                  <div className={`message-bubble ${m.role}`} style={{
                    display: 'inline-block',
                    padding: '12px 18px',
                    borderRadius: '15px',
                    maxWidth: '80%',
                    background: m.role === 'user' ? 'var(--primary)' : 'white',
                    color: m.role === 'user' ? 'white' : 'inherit',
                    boxShadow: '0 2px 10px rgba(0,0,0,0.05)',
                    textAlign: 'left'
                  }}>
                    <ReactMarkdown>{m.content}</ReactMarkdown>
                  </div>
                </div>
              ))}
              {chatLoading && <div className="spinner-sm"></div>}
            </div>

            <div className="chat-input" style={{padding: '20px', borderTop: '1px solid var(--border)', display: 'flex', gap: '10px'}}>
              <input 
                type="text" 
                placeholder="Ask anything about this document..." 
                value={input}
                onChange={(e) => setInput(e.target.value)}
                onKeyDown={(e) => e.key === 'Enter' && handleSendMessage()}
                style={{flex: 1, padding: '12px', borderRadius: '10px', border: '1px solid var(--border)'}}
              />
              <button className="btn btn-primary" onClick={handleSendMessage} disabled={chatLoading}>
                <Send size={20} />
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
};

export default DocumentTutor;
