import React, { useState, useEffect } from 'react';
import { useLocation } from 'react-router-dom';
import axios from 'axios';
import ReactMarkdown from 'react-markdown';
import { API_BASE } from '../../config';
import { BookOpen as BookOpenIcon, FileCode, Download } from 'lucide-react'; 
import './Tutor.css';

const Tutor = () => {
  const [syllabus, setSyllabus] = useState(null);
  const [program, setProgram] = useState('BA_LLB');
  const [semester, setSemester] = useState('1st_Semester');
  const [subject, setSubject] = useState('');
  const [unit, setUnit] = useState('Unit_I');
  const [topic, setTopic] = useState('');
  
  const [loading, setLoading] = useState(false);
  const [explanation, setExplanation] = useState('');
  const [error, setError] = useState('');
  const [completedTopics, setCompletedTopics] = useState(() => {
    const saved = localStorage.getItem('completedTopics');
    return saved ? JSON.parse(saved) : [];
  });

  const location = useLocation();

  useEffect(() => {
    const fetchSyllabus = async () => {
      try {
        const response = await axios.get(`${API_BASE}/api/tutor/syllabus`);
        setSyllabus(response.data);
        
        const params = new URLSearchParams(location.search);
        const urlSubject = params.get('subject');
        const urlSemester = params.get('semester');
        
        const programKey = 'BA_LLB';
        const semKey = urlSemester || '1st_Semester';
        
        if (response.data[programKey] && response.data[programKey][semKey]) {
          setSemester(semKey);
          const subjects = Object.keys(response.data[programKey][semKey]);
          if (subjects.length > 0) {
            const selectedSub = urlSubject && subjects.includes(urlSubject) ? urlSubject : subjects[0];
            setSubject(selectedSub);
          }
        }
      } catch (err) {
        setError('Failed to load syllabus.');
      }
    };
    fetchSyllabus();
  }, [location]);
  

  const handleDownloadMD = async () => {
    if (!explanation) return;
    try {
      const response = await axios.post(`${API_BASE}/api/export/save-local`, {
        title: `Study Notes ${topic}`,
        content: `# Study Notes: ${topic}\n\n${explanation}\n\n---\nGenerated by Legaify.ai`
      });
      alert(`Success! File saved to your Downloads folder: \n${response.data.filename}`);
    } catch (err) {
      console.error(err);
      alert("Failed to save file. Please check backend console.");
    }
  };

  const handleExplain = async (selectedTopic) => {
    setLoading(true);
    setError('');
    setExplanation('');
    setTopic(selectedTopic);

    try {
      const response = await fetch(`${API_BASE}/api/tutor/explain`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          program: program.replace(/_/g, ' '),
          semester: semester.replace(/_/g, ' '),
          subject: subject.replace(/_/g, ' '),
          unit: unit.replace(/_/g, ' '),
          topic: selectedTopic
        })
      });

      if (!response.ok) throw new Error("Failed to fetch explanation.");
      
      const reader = response.body.getReader();
      const decoder = new TextDecoder('utf-8');
      
      let isFirstChunk = true;

      while (true) {
        const { done, value } = await reader.read();
        if (done) break;
        
        if (isFirstChunk) {
          setLoading(false);
          isFirstChunk = false;
        }
        
        const chunk = decoder.decode(value, { stream: true });
        setExplanation((prev) => prev + chunk);
      }
    } catch (err) {
      setLoading(false);
      setError('Failed to fetch explanation. Please check your connection.');
    }
  };

  const toggleCompletion = () => {
    const topicId = `${semester}-${subject}-${topic}`;
    setCompletedTopics(prev => {
      const next = prev.includes(topicId) 
        ? prev.filter(t => t !== topicId) 
        : [...prev, topicId];
      localStorage.setItem('completedTopics', JSON.stringify(next));
      return next;
    });
  };

  if (!syllabus) return <div className="loading-state card glass">Loading KSLU Syllabus...</div>;

  const currentSubject = syllabus[program][semester][subject];

  return (
    <div className="tutor-container fade-in">
      <div className="syllabus-sidebar card glass">
        <h3 className="serif">Syllabus Navigator</h3>
        
        <div className="select-group">
          <label>Semester</label>
          <select value={semester} onChange={(e) => {
            const nextSem = e.target.value;
            setSemester(nextSem);
            const subjects = Object.keys(syllabus[program][nextSem]);
            if (subjects.length > 0) setSubject(subjects[0]);
          }}>
            {Object.keys(syllabus[program]).map(sem => (
              <option key={sem} value={sem}>{sem.replace('_', ' ')}</option>
            ))}
          </select>
        </div>

        <div className="select-group">
          <label>Subject</label>
          <select value={subject} onChange={(e) => setSubject(e.target.value)}>
            {syllabus[program][semester] && Object.keys(syllabus[program][semester]).map(s => (
              <option key={s} value={s}>{s.replace(/_/g, ' ')}</option>
            ))}
          </select>
        </div>

        <div className="units-list">
          {Object.keys(currentSubject).map(u => (
            <div key={u} className={`unit-item ${unit === u ? 'active' : ''}`} onClick={() => setUnit(u)}>
              <span className="unit-label">{u.replace('_', ' ')}</span>
              <p className="unit-title">{currentSubject[u].title}</p>
            </div>
          ))}
        </div>

        <div className="topics-list">
          <label>Topics</label>
          {currentSubject[unit].topics.map(t => (
            <button key={t} className={`topic-btn ${topic === t ? 'active' : ''}`} onClick={() => handleExplain(t)}>
              {t}
            </button>
          ))}
        </div>
      </div>

      <div className="explanation-area">
        {loading && (
          <div className="loading-state card glass">
            <div className="spinner"></div>
            <p>Your Professor is preparing the lecture on "{topic}"...</p>
          </div>
        )}

        {error && <div className="error-card card">{error}</div>}

        {explanation ? (
          <div className="explanation-content card fade-in">
            <div className="content-header" style={{display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '20px'}}>
              <div>
                <span className="badge-kslu">Exam Oriented Explanation</span>
                <h2>{topic}</h2>
              </div>
                <button 
                className="btn btn-outline" 
                onClick={handleDownloadMD}
                style={{display: 'flex', alignItems: 'center', gap: '8px', padding: '8px 16px'}}
              >
                <Download size={18} /> Download PDF
              </button>
            </div>
            
            <div className="topic-completion-bar" style={{ marginBottom: '20px', padding: '15px', background: '#f8fafc', borderRadius: '12px', display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
              <p style={{ margin: 0, fontSize: '0.95rem', fontWeight: 500 }}>
                {completedTopics.includes(`${semester}-${subject}-${topic}`) ? '✅ You have completed this topic!' : 'Have you finished studying this topic?'}
              </p>
              <button 
                className={`btn ${completedTopics.includes(`${semester}-${subject}-${topic}`) ? 'btn-success' : 'btn-primary'}`}
                onClick={toggleCompletion}
                style={{ padding: '6px 16px' }}
              >
                {completedTopics.includes(`${semester}-${subject}-${topic}`) ? 'Mark Incomplete' : 'Mark as Completed'}
              </button>
            </div>

            <div className="markdown-body">
              <ReactMarkdown>{explanation}</ReactMarkdown>
            </div>
          </div>
        ) : !loading && (
          <div className="empty-state">
            <BookOpenSVG size={64} color="#e2e8f0" />
            <h3>Select a topic to start learning</h3>
            <p>Get structured KSLU-style explanations with case laws.</p>
          </div>
        )}
      </div>
    </div>
  );
};

// Simple icon for empty state
const BookOpenSVG = ({ size, color }) => (
  <svg width={size} height={size} viewBox="0 0 24 24" fill="none" stroke={color} strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
    <path d="M4 19.5A2.5 2.5 0 0 1 6.5 17H20"></path>
    <path d="M6.5 2H20v20H6.5A2.5 2.5 0 0 1 4 19.5v-15A2.5 2.5 0 0 1 6.5 2z"></path>
  </svg>
);

export default Tutor;
