import React, { useState, useRef } from 'react';
import ReactMarkdown from 'react-markdown';
import { API_BASE } from '../../config';
import { Play, Upload, Send, Sparkles, PlayCircle, Download, X, AlertCircle, FileVideo, CheckCircle } from 'lucide-react';

const MAX_FILE_SIZE_MB = 25;
const MAX_FILE_SIZE_BYTES = MAX_FILE_SIZE_MB * 1024 * 1024;

const VideoTutor = () => {
  const [url, setUrl] = useState('');
  const [mode, setMode] = useState('youtube'); // 'youtube' | 'upload'
  const [loading, setLoading] = useState(false);
  const [summary, setSummary] = useState('');
  const [error, setError] = useState('');
  const [selectedFile, setSelectedFile] = useState(null); // { name, size }
  const [uploadProgress, setUploadProgress] = useState(''); // status text
  const fileInputRef = useRef(null);

  // ── Helpers ──────────────────────────────────────────────────────────────────

  const clearAll = () => {
    setSummary('');
    setError('');
    setUrl('');
    setSelectedFile(null);
    setUploadProgress('');
    if (fileInputRef.current) fileInputRef.current.value = '';
  };

  const handleModeSwitch = (newMode) => {
    setMode(newMode);
    setError('');
    setUploadProgress('');
    setSelectedFile(null);
    if (fileInputRef.current) fileInputRef.current.value = '';
  };

  const formatFileSize = (bytes) => {
    if (bytes < 1024 * 1024) return `${(bytes / 1024).toFixed(1)} KB`;
    return `${(bytes / (1024 * 1024)).toFixed(1)} MB`;
  };

  // ── YouTube Handler ───────────────────────────────────────────────────────────

  const handleYoutubeSummarize = async () => {
    if (!url.trim()) return;
    setLoading(true);
    setSummary('');
    setError('');

    try {
      const response = await fetch(`${API_BASE}/api/video/summarize`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ url: url.trim() }),
      });

      if (!response.ok) {
        const errData = await response.json().catch(() => ({}));
        throw new Error(errData.detail || `Server error (${response.status})`);
      }

      const reader = response.body.getReader();
      const decoder = new TextDecoder();
      while (true) {
        const { value, done } = await reader.read();
        if (done) break;
        setSummary(prev => prev + decoder.decode(value));
      }
    } catch (err) {
      setError(err.message || 'Failed to summarize YouTube video.');
    } finally {
      setLoading(false);
    }
  };

  // ── File Selection Handler ─────────────────────────────────────────────────

  const handleFileSelect = (e) => {
    const file = e.target.files[0];
    if (!file) return;

    setError('');
    setSummary('');
    setUploadProgress('');

    if (file.size > MAX_FILE_SIZE_BYTES) {
      setError(`File is too large (${formatFileSize(file.size)}). Maximum allowed size is ${MAX_FILE_SIZE_MB} MB.`);
      setSelectedFile(null);
      if (fileInputRef.current) fileInputRef.current.value = '';
      return;
    }

    setSelectedFile({ name: file.name, size: file.size });
    handleFileUpload(file);
  };

  // ── File Upload Handler ───────────────────────────────────────────────────────

  const handleFileUpload = async (file) => {
    setLoading(true);
    setSummary('');
    setError('');
    setUploadProgress('Uploading file…');

    const formData = new FormData();
    formData.append('file', file);

    try {
      const response = await fetch(`${API_BASE}/api/video/upload`, {
        method: 'POST',
        body: formData,
      });

      setUploadProgress('Transcribing with Whisper AI…');

      if (!response.ok) {
        const errData = await response.json().catch(() => ({}));
        throw new Error(errData.detail || `Server error (${response.status})`);
      }

      setUploadProgress('Generating structured notes…');

      const reader = response.body.getReader();
      const decoder = new TextDecoder();
      while (true) {
        const { value, done } = await reader.read();
        if (done) break;
        setSummary(prev => prev + decoder.decode(value));
      }

      setUploadProgress('Done!');
    } catch (err) {
      setError(err.message || 'Failed to process the video file.');
      setUploadProgress('');
    } finally {
      setLoading(false);
    }
  };

  // ── Export Handler ────────────────────────────────────────────────────────────

  const handleExport = async () => {
    if (!summary) return;
    try {
      const response = await fetch(`${API_BASE}/api/export/save-local`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          title: 'Video Lecture Notes',
          content: `# Video Lecture Notes\n\n${summary}\n\n---\nGenerated by Legaify.ai`,
        }),
      });
      const data = await response.json();
      if (!response.ok) throw new Error(data.detail || 'Export failed');
      setError('');
      // Brief success banner — reuse error state with a "success" variant
      setUploadProgress(`✓ Saved to Downloads: ${data.filename}`);
    } catch (err) {
      setError(`Export failed: ${err.message}`);
    }
  };

  // ── Render ────────────────────────────────────────────────────────────────────

  return (
    <div className="video-tutor fade-in">
      {/* Header */}
      <div className="planner-header">
        <h1 className="serif gradient-text">AI Video Tutor</h1>
        <p className="text-muted">
          Turn long legal lectures and YouTube videos into structured KSLU exam notes.
        </p>
      </div>

      {/* Mode Tabs */}
      <div style={{ display: 'flex', gap: '10px', marginBottom: '30px' }}>
        <button
          className={`btn ${mode === 'youtube' ? 'btn-primary' : 'btn-outline'}`}
          onClick={() => handleModeSwitch('youtube')}
        >
          <Play size={18} /> YouTube URL
        </button>
        <button
          className={`btn ${mode === 'upload' ? 'btn-primary' : 'btn-outline'}`}
          onClick={() => handleModeSwitch('upload')}
        >
          <Upload size={18} /> Upload Video
        </button>
      </div>

      {/* Input Card */}
      <div className="input-section card glass" style={{ padding: '40px', textAlign: 'center' }}>

        {/* ── YouTube Mode ── */}
        {mode === 'youtube' && (
          <div style={{ maxWidth: '620px', margin: '0 auto' }}>
            <PlayCircle size={48} color="var(--primary)" style={{ marginBottom: '20px' }} />
            <h3>Paste YouTube Lecture Link</h3>
            <p className="text-muted" style={{ marginBottom: '20px' }}>
              Works best with academic lectures and case law discussions.
            </p>
            <div style={{ display: 'flex', gap: '10px' }}>
              <input
                type="text"
                placeholder="https://www.youtube.com/watch?v=..."
                value={url}
                onChange={e => setUrl(e.target.value)}
                onKeyDown={e => e.key === 'Enter' && !loading && handleYoutubeSummarize()}
                disabled={loading}
                style={{
                  flex: 1,
                  padding: '12px',
                  borderRadius: '10px',
                  border: '1px solid var(--border)',
                  opacity: loading ? 0.7 : 1,
                }}
              />
              <button
                className="btn btn-primary"
                onClick={handleYoutubeSummarize}
                disabled={loading || !url.trim()}
              >
                {loading ? (
                  <span style={{ display: 'flex', alignItems: 'center', gap: '6px' }}>
                    <span className="spinner" style={{ width: 16, height: 16, borderWidth: 2 }} />
                    Analyzing…
                  </span>
                ) : (
                  <><Send size={16} /> Summarize</>
                )}
              </button>
            </div>
          </div>
        )}

        {/* ── Upload Mode ── */}
        {mode === 'upload' && (
          <div style={{ maxWidth: '620px', margin: '0 auto' }}>
            <FileVideo size={48} color="var(--primary)" style={{ marginBottom: '20px' }} />
            <h3>Upload Legal Lecture File</h3>
            <p className="text-muted" style={{ marginBottom: '6px' }}>
              Supports .mp4, .mkv, .mov, .webm, .mp3, .wav and more.
            </p>
            <p className="text-muted" style={{ marginBottom: '20px', fontSize: '0.82rem' }}>
              Max file size: <strong>{MAX_FILE_SIZE_MB} MB</strong>
            </p>

            {/* Selected file info */}
            {selectedFile && (
              <div style={{
                display: 'flex',
                alignItems: 'center',
                justifyContent: 'center',
                gap: '10px',
                marginBottom: '16px',
                padding: '10px 16px',
                borderRadius: '8px',
                background: 'var(--primary-light, #eff6ff)',
                fontSize: '0.88rem',
                color: 'var(--primary)',
              }}>
                <CheckCircle size={16} />
                <span style={{ fontWeight: 600 }}>{selectedFile.name}</span>
                <span style={{ opacity: 0.7 }}>({formatFileSize(selectedFile.size)})</span>
              </div>
            )}

            {/* Upload progress status */}
            {loading && uploadProgress && (
              <div style={{
                display: 'flex',
                alignItems: 'center',
                justifyContent: 'center',
                gap: '10px',
                marginBottom: '16px',
                fontSize: '0.9rem',
                color: 'var(--primary)',
              }}>
                <span className="spinner" style={{ width: 18, height: 18, borderWidth: 2 }} />
                {uploadProgress}
              </div>
            )}

            {/* Done status */}
            {!loading && uploadProgress && uploadProgress.startsWith('✓') && (
              <p style={{ color: 'green', marginBottom: '12px', fontSize: '0.88rem' }}>
                {uploadProgress}
              </p>
            )}

            <label
              className={`btn ${loading ? 'btn-outline' : 'btn-primary'}`}
              style={{ cursor: loading ? 'not-allowed' : 'pointer', opacity: loading ? 0.7 : 1 }}
            >
              {loading ? 'Processing…' : selectedFile ? 'Change File' : 'Select Video File'}
              <input
                ref={fileInputRef}
                type="file"
                onChange={handleFileSelect}
                hidden
                disabled={loading}
                accept="video/*,audio/*,.mp4,.mkv,.mov,.webm,.mp3,.wav,.m4a,.ogg"
              />
            </label>
          </div>
        )}
      </div>

      {/* Error Banner */}
      {error && (
        <div style={{
          display: 'flex',
          alignItems: 'flex-start',
          gap: '12px',
          marginTop: '20px',
          padding: '16px 20px',
          borderRadius: '12px',
          background: '#fef2f2',
          border: '1px solid #fecaca',
          color: '#b91c1c',
          fontSize: '0.9rem',
        }}>
          <AlertCircle size={20} style={{ flexShrink: 0, marginTop: 1 }} />
          <span style={{ flex: 1 }}>{error}</span>
          <button
            onClick={() => setError('')}
            style={{ background: 'none', border: 'none', cursor: 'pointer', color: '#b91c1c', padding: 0 }}
          >
            <X size={18} />
          </button>
        </div>
      )}

      {/* Summary Result */}
      {summary && (
        <div
          className="summary-result card fade-in"
          style={{ marginTop: '40px', borderLeft: '5px solid var(--gold)' }}
        >
          <div style={{
            display: 'flex',
            alignItems: 'center',
            justifyContent: 'space-between',
            marginBottom: '20px',
            flexWrap: 'wrap',
            gap: '12px',
          }}>
            <div style={{ display: 'flex', alignItems: 'center', gap: '10px' }}>
              <Sparkles size={24} color="var(--gold)" />
              <h2 className="serif">AI Generated Notes</h2>
            </div>
            <div style={{ display: 'flex', gap: '10px' }}>
              <button
                className="btn btn-outline"
                onClick={handleExport}
                style={{ display: 'flex', alignItems: 'center', gap: '8px' }}
              >
                <Download size={18} /> Save to Downloads
              </button>
              <button
                className="btn btn-outline"
                onClick={clearAll}
                style={{ display: 'flex', alignItems: 'center', gap: '8px' }}
              >
                <X size={18} /> New Video
              </button>
            </div>
          </div>

          <div className="markdown-body">
            <ReactMarkdown>{summary}</ReactMarkdown>
          </div>
        </div>
      )}
    </div>
  );
};

export default VideoTutor;
